spring:
  banner:
    location: classpath:banner.txt
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:cep-validation}
    password: ${RABBITMQ_PASSWORD:cep-validation}
    template:
      reply-timeout: 6000000

rao-runner-server:
  amqp:
    queue-name: ${RAO_ADAPTER_SERVER_QUEUE_NAME:rao-runner}

dichotomy-server:
  requests:
    queue-name: ${RAO_DICHOTOMY_SERVER_QUEUE_NAME:dichotomy-requests}
  responses:
    exchange: dichotomy-response
    expiration: 60000
  minio:
    access:
      name: ${MINIO_USERNAME:cep-validation}
      secret: ${MINIO_PASSWORD:cep-validation}
    url: http://${MINIO_HOST:localhost}:${MINIO_PORT:9000}
    bucket: ${MINIO_BUCKET:cep-validation}
    base-path: ${RAO_DICHOTOMY_SERVER_MINIO_BASE_PATH:dichotomy/}
  security:
    whitelist:
      - http://${MINIO_HOST:localhost}:${MINIO_PORT:9000}

server:
  port: ${RAO_DICHOTOMY_SERVER_PORT:8080}